### ISSUE TITLE
Purpose of database/ files - delete if obselete

### ISSUE THREAD

**Issue by softwareengineerprogrammer** [NREL/python-geophires-x#25]
@malcolm-dsider are the files in https://github.com/NREL/python-geophires-x/tree/main/src/geophires_x/database relevant any more? If not we should delete them

**Comment by malcolm-dsider** [comment]
No, not really. It is good stuff, but not included in this release. I’ll hang onto a local copy on my machine in case we decide to implement something like it.

 

From: Jonathan Pezzino ***@***.***> 
Sent: Thursday, October 19, 2023 4:46 PM
To: NREL/python-geophires-x ***@***.***>
Cc: Malcolm Ross ***@***.***>; Mention ***@***.***>
Subject: [NREL/python-geophires-x] Purpose of database/ files - delete if obselete (Issue #25)

 

@malcolm-dsider <https://github.com/malcolm-dsider>  are the files in https://github.com/NREL/python-geophires-x/tree/main/src/geophires_x/database relevant any more? If not we should delete them

**Comment by softwareengineerprogrammer** [comment]
Thanks @malcolm-dsider, included deletion in https://github.com/NREL/python-geophires-x/pull/24

For what it's worth the files will always be accessible in git history if you happen to lose the copies on your local machine, you just need to look at files at commits prior to deletion; for example this link will always work to access them: https://github.com/NREL/python-geophires-x/tree/a05364f1b08c3252bad6e1af1c791a09f892144a/src/geophires_x/database
