### ISSUE TITLE
Delete AdvModel, related unused code

### ISSUE THREAD

**Issue by softwareengineerprogrammer** [NREL/python-geophires-x#32]
AdvModel and some related classes are unused and appear to have been made obselete/redundant by https://github.com/NREL/python-geophires-x/commit/79d4f1124f5a55c5fb54a547bf00fd71d3fc6a1a. We should delete it if possible to increase code coverage - @malcolm-dsider can you confirm it's no longer needed?

**Comment by malcolm-dsider** [comment]
Confirmed.

 

From: Jonathan Pezzino ***@***.***> 
Sent: Thursday, November 2, 2023 4:57 PM
To: NREL/python-geophires-x ***@***.***>
Cc: Malcolm Ross ***@***.***>; Mention ***@***.***>
Subject: [NREL/python-geophires-x] Delete AdvModel, related unused code (Issue #32)

 

AdvModel and some related classes is unused and appear to have been made obselete/redundant by  <https://github.com/NREL/python-geophires-x/commit/79d4f1124f5a55c5fb54a547bf00fd71d3fc6a1a> 79d4f11. We should delete it if possible to increase code coverage - @malcolm-dsider <https://github.com/malcolm-dsider>  can you confirm it's no longer needed?
