### ISSUE TITLE
Enable Secret Scanning

### ISSUE THREAD

**Issue by softwareengineerprogrammer** [NREL/python-geophires-x#53]
Enable secret scanning in https://github.com/NREL/python-geophires-x/security (requires administrative privileges I don't have)

<img width="817" alt="Screenshot 2023-11-11 at 15 38 01" src="https://github.com/NREL/python-geophires-x/assets/4056124/a79df584-3688-4524-a06c-e18db48d19b8">

**Comment by kfbeckers** [comment]
Enabled now
