### ISSUE TITLE
Typo in example12_DH.txt

### ISSUE THREAD

**Issue by softwareengineerprogrammer** [NREL/python-geophires-x#56]
2 params have a typo of "Lengt" instead of "Length": https://github.com/NREL/python-geophires-x/blob/bbb9a173f24030acdb17daf01bbb78d6c8e34265/tests/examples/example12_DH.txt#L77-L78

When I fix the typos locally the corresponding test fails, presumably due to those parameters now being correctly taken into account. Assigning to @kfbeckers to verify that the output when the typos are fixed is accurate.

**Comment by kfbeckers** [comment]
Fixed with PR https://github.com/NREL/python-geophires-x/pull/61
